### ISSUE TITLE
/vote abstain is broken

### ISSUE THREAD

**Issue by ShaunOfTheLive** [ShaunOfTheLive/HangoutsBot#4]

**Comment by ShaunOfTheLive** [comment]
AttributeError: 'NoneType' object has no attribute 'format'

Traceback (most recent call last):
  File "/home/shill/HangoutsBot/Core/Commands/Dispatcher.py", line 45, in run
    yield from func(bot, event, _args, *_kwds)
  File "/usr/local/opt/python-3.4.3/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(_args, *_kw)
  File "/home/shill/HangoutsBot/Core/Commands/DefaultCommands.py", line 562, in vote
    bot.send_message(event.conv, 'User {} has abstained from voting.').format(event.user.full_name)

**Comment by ShaunOfTheLive** [comment]
Fixed upstream.
